### ISSUE TITLE
Error in example

### ISSUE THREAD

**Issue by tomleo** [mobinni/grunt-typeset#2]
``` javascript
    files: {
      [
        '*.html',
        '**/*.html',
        'index.html'
      ]
    },
```

It looks like you have a list as a key, but no value.

**Comment by simonlc** [comment]
It's also missing a target:

```
grunt.initConfig({
  typeset: {
    options: {
      ignore: '.skip, #anything, .which-matches', // string of a CSS selector to skip
      only: '#only-typeset, .these-elements'    // string of a CSS selector to only apply typeset
    },
    dist: {
      files: [
          '*.html',
          '**/*.html',
          'index.html'
        ],
    },
  },
});
```

**Comment by mobinni** [comment]
It does not take target files indeed, but it does have an option for destination. Updating readme.

**Comment by mobinni** [comment]
Hey, I'm sorry I didn't follow the conventions. Thing is I needed a grunt plugin fast for a specific use-case so I built it and shared it on the fly, feel free to contribute tho. Will try to implement if and when I have time.

**Comment by simonlc** [comment]
Hey, no problem, I'm glad you shared it, I got it working after reading the source. Saved me the time of making it myself.
